INFO - 2022-10-29 18:28:34,610 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:28:34,612 - Server avviato con successo...
INFO - 2022-10-29 18:28:54,018 - Richiesta procedura di iscrizione: [mariobianchi@gmail.com,ret,a,a,Turista,1111 1111 1111 1111]
ERROR - 2022-10-29 18:28:54,019 - Exception calling application: userType_d
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 107, in SignUp
    ret = storeUser(SignUpInfo.email, SignUpInfo.username, SignUpInfo.password, SignUpInfo.userType_d, SignUpInfo.airline, SignUpInfo.cartaDiCredito, SignUpInfo.userType)
AttributeError: userType_d
INFO - 2022-10-29 18:30:24,275 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:30:24,276 - Server avviato con successo...
INFO - 2022-10-29 18:30:40,645 - Richiesta procedura di iscrizione: [mariobianchi@gmail.com,ret,a,a,Turista,1111 1111 1111 1111]
INFO - 2022-10-29 18:30:41,771 - Procedura di iscrizione conclusa con successo: [mariobianchi@gmail.com,ret,a,a,Turista]
INFO - 2022-10-29 18:32:42,863 - Richiesta procedura di iscrizione: [user0@gmail.com,user0,user0,user0,Turista,1111 1111 1111 1111]
INFO - 2022-10-29 18:32:43,475 - Procedura di iscrizione conclusa con successo: [user0@gmail.com,user0,user0,user0,Turista]
INFO - 2022-10-29 18:33:42,731 - Richiesta procedura di iscrizione: [mariorossi@gmail.com,user0,a,a,Turista,1111 2222 3333 4444]
WARNING - 2022-10-29 18:33:42,732 - Procedura di iscrizione conclusa senza successo: [mariorossi@gmail.com,user0,a,a,Turista]
INFO - 2022-10-29 18:36:44,814 - Richiesta procedura di accesso: [user0,user0]
ERROR - 2022-10-29 18:36:45,472 - Exception calling application: An error occurred (ValidationException) when calling the GetItem operation: The provided key element does not match the schema
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 147, in SignIn
  File "/home/cap/progetto/progetto-SDCC/code/registration/RegDB.py", line 109, in retrieveUser
    response = table.get_item(
  File "/usr/lib/python3/dist-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the GetItem operation: The provided key element does not match the schema
INFO - 2022-10-29 18:38:28,958 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:38:28,959 - Server avviato con successo...
INFO - 2022-10-29 18:38:40,178 - Richiesta procedura di accesso: [user0,user0]
ERROR - 2022-10-29 18:38:40,932 - Exception calling application: __str__ returned non-string (type bytes)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 139, in SignIn
    user = retrieveUser(Credentials.username, Credentials.password)
  File "/home/cap/progetto/progetto-SDCC/code/registration/RegDB.py", line 149, in retrieveUser
    print("USER TYPE VALUE: " + str(userType))
TypeError: __str__ returned non-string (type bytes)
INFO - 2022-10-29 18:39:33,808 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:39:33,809 - Server avviato con successo...
INFO - 2022-10-29 18:39:37,682 - Richiesta procedura di accesso: [user0,user0]
ERROR - 2022-10-29 18:39:38,504 - Exception calling application: __str__ returned non-string (type bytes)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 139, in SignIn
    user = retrieveUser(Credentials.username, Credentials.password)
  File "/home/cap/progetto/progetto-SDCC/code/registration/RegDB.py", line 149, in retrieveUser
    print(userType)
TypeError: __str__ returned non-string (type bytes)
INFO - 2022-10-29 18:40:16,865 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:40:16,867 - Server avviato con successo...
INFO - 2022-10-29 18:40:19,345 - Richiesta procedura di accesso: [user0,user0]
ERROR - 2022-10-29 18:40:20,137 - Exception calling application: 'Binary' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 139, in SignIn
    user = retrieveUser(Credentials.username, Credentials.password)
  File "/home/cap/progetto/progetto-SDCC/code/registration/RegDB.py", line 149, in retrieveUser
    print(userType.decode('utf-8'))
AttributeError: 'Binary' object has no attribute 'decode'
INFO - 2022-10-29 18:41:26,464 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:41:26,508 - Server avviato con successo...
INFO - 2022-10-29 18:41:29,810 - Richiesta procedura di accesso: [user0,user0]
ERROR - 2022-10-29 18:41:30,918 - Exception calling application: object of type 'Binary' has no len()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 139, in SignIn
    user = retrieveUser(Credentials.username, Credentials.password)
  File "/home/cap/progetto/progetto-SDCC/code/registration/RegDB.py", line 151, in retrieveUser
    print(len(userType))
TypeError: object of type 'Binary' has no len()
INFO - 2022-10-29 18:43:01,339 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:43:01,340 - Server avviato con successo...
INFO - 2022-10-29 18:43:05,148 - Richiesta procedura di accesso: [user0,user0]
ERROR - 2022-10-29 18:43:06,550 - Exception calling application: object of type 'Binary' has no len()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 139, in SignIn
    user = retrieveUser(Credentials.username, Credentials.password)
  File "/home/cap/progetto/progetto-SDCC/code/registration/RegDB.py", line 151, in retrieveUser
    print(len(userType))
TypeError: object of type 'Binary' has no len()
INFO - 2022-10-29 18:44:02,106 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:44:02,107 - Server avviato con successo...
INFO - 2022-10-29 18:44:04,814 - Richiesta procedura di accesso: [user0,user0]
ERROR - 2022-10-29 18:44:06,197 - Exception calling application: 'Binary' object has no attribute 'eq'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 139, in SignIn
    user = retrieveUser(Credentials.username, Credentials.password)
  File "/home/cap/progetto/progetto-SDCC/code/registration/RegDB.py", line 149, in retrieveUser
    print(userType.eq(bytes(0)))
AttributeError: 'Binary' object has no attribute 'eq'
INFO - 2022-10-29 18:44:33,816 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:44:33,817 - Server avviato con successo...
INFO - 2022-10-29 18:44:37,594 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 18:44:38,858 - Procedura di accesso conclusa con successo: [user0,user0]
ERROR - 2022-10-29 18:44:38,861 - Exception calling application: bad argument type for built-in operation
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 146, in SignIn
    output = Registration_pb2.SignInResponse(storedType=user.storedType, isCorrect=user.isCorrect)
TypeError: bad argument type for built-in operation
INFO - 2022-10-29 18:46:39,621 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:46:39,623 - Server avviato con successo...
INFO - 2022-10-29 18:46:43,718 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 18:46:44,516 - Procedura di accesso conclusa con successo: [user0,user0]
ERROR - 2022-10-29 18:46:44,516 - Exception calling application: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 148, in SignIn
    output = Registration_pb2.SignInResponse(storedType=value, isCorrect=user.isCorrect)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
INFO - 2022-10-29 18:48:13,500 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:48:13,501 - Server avviato con successo...
INFO - 2022-10-29 18:48:28,062 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 18:48:29,472 - Procedura di accesso conclusa con successo: [user0,user0]
ERROR - 2022-10-29 18:48:29,475 - Exception calling application: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 148, in SignIn
    output = Registration_pb2.SignInResponse(storedType=value, isCorrect=user.isCorrect)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
INFO - 2022-10-29 18:57:37,981 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 18:57:37,982 - Server avviato con successo...
INFO - 2022-10-29 18:57:42,441 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 18:57:43,509 - Procedura di accesso conclusa con successo: [user0,user0]
ERROR - 2022-10-29 18:57:43,511 - Exception calling application: bad argument type for built-in operation
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 148, in SignIn
    output = Registration_pb2.SignInResponse(storedType=value, isCorrect=user.isCorrect)
TypeError: bad argument type for built-in operation
INFO - 2022-10-29 19:01:29,043 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 19:01:29,044 - Server avviato con successo...
INFO - 2022-10-29 19:02:39,884 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 19:02:39,886 - Server avviato con successo...
INFO - 2022-10-29 19:03:13,070 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 19:03:13,071 - Server avviato con successo...
INFO - 2022-10-29 19:03:34,159 - Richiesta procedura di iscrizione: [u@gmail.com,user0@gmail.com,user0,usero0,Turista,1111 1111 1111 1111]
WARNING - 2022-10-29 19:03:34,162 - Procedura di iscrizione conclusa senza successo: [u@gmail.com,user0@gmail.com,user0,usero0,Turista]
INFO - 2022-10-29 19:04:12,100 - Richiesta procedura di iscrizione: [u@gmail.com,user0,user0,user0,Turista,1111 1111 1111 1111]
INFO - 2022-10-29 19:04:12,944 - Procedura di iscrizione conclusa con successo: [u@gmail.com,user0,user0,user0,Turista]
INFO - 2022-10-29 19:05:19,122 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 19:05:20,018 - Procedura di accesso conclusa con successo: [user0,user0]
ERROR - 2022-10-29 19:05:20,019 - Exception calling application: bad argument type for built-in operation
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 148, in SignIn
    output = Registration_pb2.SignInResponse(storedType=value, isCorrect=user.isCorrect)
TypeError: bad argument type for built-in operation
INFO - 2022-10-29 19:05:41,368 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 19:05:41,369 - Server avviato con successo...
INFO - 2022-10-29 19:05:46,761 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 19:05:47,724 - Procedura di accesso conclusa con successo: [user0,user0]
ERROR - 2022-10-29 19:05:47,725 - Exception calling application: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 148, in SignIn
    output = Registration_pb2.SignInResponse(storedType=value, isCorrect=user.isCorrect)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
INFO - 2022-10-29 19:06:44,624 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 19:06:44,626 - Server avviato con successo...
INFO - 2022-10-29 19:06:54,164 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 19:06:55,173 - Procedura di accesso conclusa con successo: [user0,user0]
INFO - 2022-10-29 19:07:32,291 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 19:07:32,296 - Server avviato con successo...
INFO - 2022-10-29 19:07:42,977 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 19:07:43,736 - Procedura di accesso conclusa con successo: [user0,user0]
INFO - 2022-10-29 19:09:17,954 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 19:09:19,580 - Procedura di accesso conclusa con successo: [user0,user0]
INFO - 2022-10-29 19:11:56,234 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 19:11:56,235 - Server avviato con successo...
INFO - 2022-10-29 19:12:10,701 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 19:12:11,440 - Procedura di accesso conclusa con successo: [user0,user0]
INFO - 2022-10-29 19:14:22,161 - Richiesta procedura di iscrizione: [user1@gmail.com,user1,user1,user1,Turista,1111 1111 1111 1111]
INFO - 2022-10-29 19:14:23,675 - Procedura di iscrizione conclusa con successo: [user1@gmail.com,user1,user1,user1,Turista]
INFO - 2022-10-29 19:43:53,870 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 19:43:53,889 - Server avviato con successo...
INFO - 2022-10-29 19:45:02,946 - Richiesta procedura di iscrizione: [user0@gmail.com,user0,user0,user0,Turista,1111 1111 1111 1111]
INFO - 2022-10-29 19:45:03,478 - Procedura di iscrizione conclusa con successo: [user0@gmail.com,user0,user0,user0,Turista]
INFO - 2022-10-29 19:45:20,063 - Richiesta procedura di accesso: [user0,user]
WARNING - 2022-10-29 19:45:20,728 - Procedura di accesso conclusa senza successo: [user0,user]
ERROR - 2022-10-29 19:45:20,728 - Exception calling application: 'NoneType' object has no attribute '__bytes__'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cap/progetto/progetto-SDCC/code/registration/registration.py", line 146, in SignIn
    value = user.storedType.__bytes__()
AttributeError: 'NoneType' object has no attribute '__bytes__'
INFO - 2022-10-29 19:48:10,626 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 19:48:10,627 - Server avviato con successo...
INFO - 2022-10-29 19:48:18,885 - Richiesta procedura di accesso: [ciao,ciao]
WARNING - 2022-10-29 19:48:20,109 - Procedura di accesso conclusa senza successo: [ciao,ciao]
INFO - 2022-10-29 19:48:37,629 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 19:48:38,287 - Procedura di accesso conclusa con successo: [user0,user0]
INFO - 2022-10-29 19:48:49,802 - Richiesta procedura di accesso: [ciao,o]
WARNING - 2022-10-29 19:48:50,504 - Procedura di accesso conclusa senza successo: [ciao,o]
INFO - 2022-10-29 19:48:58,853 - Richiesta procedura di accesso: [user1,user2]
WARNING - 2022-10-29 19:48:59,511 - Procedura di accesso conclusa senza successo: [user1,user2]
INFO - 2022-10-29 19:49:04,551 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 19:49:05,213 - Procedura di accesso conclusa con successo: [user0,user0]
INFO - 2022-10-29 19:51:26,736 - Richiesta procedura di iscrizione: [user0@gmail.com,user0,ciao,ciao,Turista,1111 1111 1111 1111]
WARNING - 2022-10-29 19:51:26,736 - Procedura di iscrizione conclusa senza successo: [user0@gmail.com,user0,ciao,ciao,Turista]
INFO - 2022-10-29 19:52:03,859 - Richiesta procedura di iscrizione: [user1@gmail.com,user1,user1,user1,Compagnia aerea,1111 2222 3333 4444]
INFO - 2022-10-29 19:52:04,850 - Procedura di iscrizione conclusa con successo: [user1@gmail.com,user1,user1,user1,Compagnia aerea]
INFO - 2022-10-29 19:52:20,517 - Richiesta procedura di accesso: [user1,user1]
INFO - 2022-10-29 19:52:21,142 - Procedura di accesso conclusa con successo: [user1,user1]
INFO - 2022-10-29 19:54:07,221 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 19:54:07,223 - Server avviato con successo...
INFO - 2022-10-29 19:54:23,175 - Richiesta procedura di accesso: [user1,user1]
INFO - 2022-10-29 19:54:23,910 - Procedura di accesso conclusa con successo: [user1,user1]
INFO - 2022-10-29 19:56:12,596 - Richiesta procedura di accesso: [user1,user1]
INFO - 2022-10-29 19:56:13,266 - Procedura di accesso conclusa con successo: [user1,user1]
INFO - 2022-10-29 19:57:50,520 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 19:57:50,521 - Server avviato con successo...
INFO - 2022-10-29 19:57:59,711 - Richiesta procedura di accesso: [user,ii]
WARNING - 2022-10-29 19:58:00,440 - Procedura di accesso conclusa senza successo: [user,ii]
INFO - 2022-10-29 19:58:06,748 - Richiesta procedura di accesso: [user1,user1]
INFO - 2022-10-29 19:58:07,400 - Procedura di accesso conclusa con successo: [user1,user1]
INFO - 2022-10-29 20:00:20,973 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-29 20:00:20,986 - Server avviato con successo...
INFO - 2022-10-29 20:00:32,586 - Richiesta procedura di accesso: [user1,user1]
INFO - 2022-10-29 20:00:33,297 - Procedura di accesso conclusa con successo: [user1,user1]
INFO - 2022-10-29 20:02:02,886 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 20:02:03,542 - Procedura di accesso conclusa con successo: [user0,user0]
INFO - 2022-10-29 20:02:29,101 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-29 20:02:29,778 - Procedura di accesso conclusa con successo: [user0,user0]
INFO - 2022-10-29 20:05:14,864 - Richiesta procedura di iscrizione: [i@kk,user0,k,k,Turista,1111 1111 1111]
WARNING - 2022-10-29 20:05:14,864 - Procedura di iscrizione conclusa senza successo: [i@kk,user0,k,k,Turista]
INFO - 2022-10-29 20:05:24,399 - Richiesta procedura di iscrizione: [i@kk,user1,k,k,Turista,1111 1111 1111]
WARNING - 2022-10-29 20:05:24,400 - Procedura di iscrizione conclusa senza successo: [i@kk,user1,k,k,Turista]
INFO - 2022-10-29 20:05:29,041 - Richiesta procedura di iscrizione: [i@kk,user2,k,k,Turista,1111 1111 1111]
INFO - 2022-10-29 20:05:29,631 - Procedura di iscrizione conclusa con successo: [i@kk,user2,k,k,Turista]
INFO - 2022-10-31 16:16:40,615 - Avvio del server in ascolto sulla porta 50051...
INFO - 2022-10-31 16:16:40,623 - Server avviato con successo...
INFO - 2022-10-31 16:17:44,125 - Richiesta procedura di accesso: [o,o]
WARNING - 2022-10-31 16:17:45,283 - Procedura di accesso conclusa senza successo: [o,o]
INFO - 2022-10-31 16:18:20,134 - Richiesta procedura di iscrizione: [user0@gmail.com,user0,user0,user0,Turista,1111 2222 3333 4444]
INFO - 2022-10-31 16:18:20,764 - Procedura di iscrizione conclusa con successo: [user0@gmail.com,user0,user0,user0,Turista]
INFO - 2022-10-31 16:20:01,327 - Richiesta procedura di accesso: [user0,user0]
INFO - 2022-10-31 16:20:01,977 - Procedura di accesso conclusa con successo: [user0,user0]
